name: 'Get Dockerfile Timestamp'
description: 'Retrieves the last commit timestamp of Dockerfile'

outputs:
  timestamp:
    description: 'Timestamp of last Dockerfile commit'
    value: ${{ steps.get-timestamp.outputs.timestamp }}

runs:
  using: "composite"
  steps:
    - id: get-timestamp
      shell: bash
      run: |
        COMMIT_TIMESTAMP=$(git show -s --format='%Y%m%d%H%M%S' $COMMIT_HASH -- Dockerfile)
        echo "timestamp=$COMMIT_TIMESTAMP" >> $GITHUB_OUTPUT
        echo "Retrieved Dockerfile timestamp: $COMMIT_TIMESTAMP"