name: 'Docker Build and Push Operations'
description: 'Handles Docker image building and pushing based on timestamp comparison'

inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  dockerfile-timestamp:
    description: 'Timestamp of Dockerfile last commit'
    required: true
  image-timestamp:
    description: 'Timestamp of last image push'
    required: true
  ghcr-token:
    description: 'GHCR PAT token'
    required: true

outputs:
  docker_image_tag:
    description: 'Generated Docker image tag'
    value: ${{ steps.build-push.outputs.docker_image_tag }}

runs:
  using: "composite"
  steps:
    - id: build-push
      shell: bash
      run: |
        if [ "${{ inputs.dockerfile-timestamp }}" -gt "${{ inputs.image-timestamp }}" ]; then
          echo "Dockerfile has been updated. Building a new image."
          docker_image_tag=$(date +'%Y%m%d%H%M%S')
          echo "docker_image_tag=$docker_image_tag" >> $GITHUB_OUTPUT
          
          docker build -t ghcr.io/niranjanorgground/${{ inputs.image-name }}:latest \
                      -t ghcr.io/niranjanorgground/${{ inputs.image-name }}:$docker_image_tag \
                      -f $GITHUB_WORKSPACE/Dockerfile .
          
          echo "${{ inputs.ghcr-token }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          
          docker push ghcr.io/niranjanorgground/${{ inputs.image-name }}:latest
          docker push ghcr.io/niranjanorgground/${{ inputs.image-name }}:$docker_image_tag
        else
          echo "No update to Dockerfile. Using latest image."
          echo "The Dockerfile was last updated on ${{ inputs.dockerfile-timestamp }}"
        fi