name: Build and Push

on:
  # push:
  #   branches: main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read  # To access the repository contents
  packages: write  # To push to GHCR
  actions: read  # To allow the workflow to access actions

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the ${{github.repository}} repo
        uses: actions/checkout@v4.2.2

      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            ghcr.io/niranjanorgground/docker-test:latest
            ghcr.io/niranjanorgground/docker-test:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          labels: ${{ steps.meta.outputs.labels }}
