name: ARC Scaleset Creation with Docker Image Check

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'Docker image name'
        required: true

jobs:
  check-and-build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      docker_image_tag: ${{ steps.set-docker-tag.outputs.docker_image_tag }}

    steps:
      - name: Checkout service repository
        uses: actions/checkout@v4

      - name: Get last commit timestamp of Dockerfile
        id: dockerfile-commit
        run: |
          COMMIT_TIMESTAMP=$(git -C $(pwd) log -1 --format="%cd" --date=format:'%Y%m%d%H%M' -- Dockerfile)
          echo "COMMIT_TIMESTAMP=$COMMIT_TIMESTAMP" >> $GITHUB_ENV
          echo $COMMIT_TIMESTAMP

      - name: Get last push timestamp of Docker image from GHCR
        id: image-push-timestamp
        run: |
          # Fetch the list of versions from the GitHub Container Registry API
          echo "LAST_PUSH_TIMESTAMP=$(curl -s -H "Authorization: token ${{ secrets.GHCR_PAT }}" "https://api.github.com/orgs/niranjanorgground/packages/container/${{inputs.IMAGE_NAME}}/versions" | jq -r '.[0].created_at' | xargs -I {} date -d {} +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          echo ${{env.LAST_PUSH_TIMESTAMP}}

      # - name: Compare timestamps and push to registry
      #   id: set-docker-tag
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     if [ "$COMMIT_TIMESTAMP" -gt "$PUSH_TIMESTAMP" ]; then
      #       echo "Dockerfile has been updated. Building a new image."
      #       docker_image_tag=$(date +'%Y%m%d%H%M')
      #       echo "docker_image_tag=$docker_image_tag" >> $GITHUB_ENV

      #       docker build -t ghcr.io/$GITHUB_OWNER/$IMAGE_NAME:latest -t ghcr.io/$GITHUB_OWNER/$IMAGE_NAME:$docker_image_tag -f $GITHUB_WORKSPACE/Dockerfile .

      #       # Log in to GitHub Container Registry
      #       echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      #       # Push both tags to GHCR
      #       docker push ghcr.io/$GITHUB_OWNER/$IMAGE_NAME:latest
      #       docker push ghcr.io/$GITHUB_OWNER/$IMAGE_NAME:$docker_image_tag
      #     else
      #       echo "No update to Dockerfile. Using latest image."
      #       echo "The Dockerfile is last updated on $COMMIT_TIMESTAMP"
      #     fi
